---
version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    restart: on-failure
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

#  config-server:
#    image: ahmadnawawi99/microservices:config-server
#    container_name: config-server
#    ports:
#      - "8090:8090"
#    expose:
#      - "8090"

  discovery-server:
    image: ahmadnawawi99/discovery-server:0.0.1-SNAPSHOT
    pull_policy: always
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#    depends_on:
#      - config-server

  api-gateway:
    image: ahmadnawawi99/api-gateway:0.0.1-SNAPSHOT
    pull_policy: always
    container_name: api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery-server
      #- config-server
    extra_hosts:
      - "mongo:192.168.253.1"

  authentication-service:
    container_name: authentication-service
    image: ahmadnawawi99/authentication-service:0.0.1-SNAPSHOT
    pull_policy: always
    ports:
      - "8091:8091"
    expose:
      - "8091"
    extra_hosts:
      - "mongo:192.168.253.1"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-server
      - api-gateway
      #- config-server

  product-service:
    container_name: product-service
    image: ahmadnawawi99/product-service:0.0.1-SNAPSHOT
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-server
      - api-gateway
    extra_hosts:
      - "mongo:192.168.253.1"

  order-service:
    container_name: order-service
    image: ahmadnawawi99/order-service:0.0.1-SNAPSHOT
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - broker
      - discovery-server
      - api-gateway
      - rabbitmq
    extra_hosts:
      - "mongo:192.168.253.1"

  inventory-service:
    container_name: inventory-service
    image: ahmadnawawi99/inventory-service:0.0.1-SNAPSHOT
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-server
      - api-gateway
      #- config-server
    extra_hosts:
      - "mongo:192.168.253.1"

  notification-service:
    container_name: notification-service
    image: ahmadnawawi99/notification-service:0.0.1-SNAPSHOT
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-server
      - api-gateway
      - broker

  payment-service:
    container_name: payment-service
    image: ahmadnawawi99/payment-service:0.0.1-SNAPSHOT
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - discovery-server
      - api-gateway
      - rabbitmq